@startuml

skinparam linetype polyline
hide empty members

note as id_note
  all interfaces also
  have a property
  `id: number`
  which is the PK.
end note

interface Book extends Medium {
  authors: Person[];
  seriess: BookSeries[];
  releases: BookRelease[];
}

interface BookSeries {
  title: string;
  books: Book[];
}

interface BookRelease {
  book: Book;
  medium: BookReleaseMedium;
  publisher: string;
  country?: Country;
  notes?: EditorJsOutputData;
  releaseCollection?: ReleaseCollection;
}

enum BookReleaseMedium {
  hardcover
  paperback
  ebook
  audiobook
  other
  unknown
}

interface Country {
  alpha2Code: string;
  alpha3Code: string;
  books: Book[];
  bookReleases: BookRelease[];
  films: Film[];
  filmReleases: FilmRelease[];
}

interface Film extends Medium {
  directors: Person[];
  actors: Person[];
  producers: Person[];
  productionStudios: Studio[];
  distributionStudios: Studio[];
  seriess: FilmSeries[];
  releases: FilmRelease[];
}

interface FilmSeries {
  title: string;
  films: Film[];
}

interface FilmRelease {
  film: Film;
  medium: FilmReleaseMedium;
  label: string;
  country?: Country;
  notes?: EditorJsOutputData;
  packaging: FilmReleasePackaging;
  edition?: string;
  releaseCollection?: ReleaseCollection;
  rating?: Rating;
}

enum FilmReleaseMedium {
  uhdbluray
  bluray
  hddvd
  dvd
  tv
  vod
  ld
  vcd
  vhs
  other
  unknown
}

enum FilmReleasePackaging {
  softcase
  digipack
  hardbox
  insert
  metalpak
  mediabook
  steelbook
  tinbox
  other
  unknown
}

interface Genre {
  title: string;
  slug: string;
  books: Book[];
  films: Film[];
}

interface Medium {
  title: string;
  originalTitle?: string;
  internationalTitle?: string;
  alternativeTitles?: string;
  year?: string;
  genres: Genre[];
  countries: Country[];
  synopsis?: string;
}

interface MyBook {
  book: Book;
  didRead: boolean;
  wantToRead: boolean;
  position?: MyPosition;
  user: User;
  addedAt?: Date;
}

interface MyBookRelease {
  book: Book;
  buyingPrice?: number;
  currentValue?: number;
  didRead: boolean;
  wantToRead: boolean;
  position?: MyPosition;
  user: User;
  addedAt?: Date;
}

interface MyFilm {
  film: Film;
  didWatch: boolean;
  wantToWatch: boolean;
  position?: MyPosition;
  user: User;
  addedAt?: Date;
}

interface MyFilmRelease {
  film: Film;
  buyingPrice?: number;
  currentValue?: number;
  didWatch: boolean;
  wantToWatch: boolean;
  position?: MyPosition;
  user: User;
  addedAt?: Date;
}

interface MyPosition {
  title: string;
  user: User;
}

interface Person {
  displayName: string;
  firstName?: string;
  familyName?: string;
  directedFilms: Film[];
  actedFilms: Film[];
  producedFilms: Film[];
  writtenBooks: Book[];
}

interface Rating {
  title: string;
  filmReleases: FilmRelease[];
}

interface ReleaseCollection {
  title: string;
  bookReleases: BookRelease[];
  filmReleases: FilmRelease[];
}

interface Studio {
  displayName: string;
  producedFilms: Film[];
  distributedFilms: Film[];
}

interface Translation {
  bookReleaseMedium: Record<BookReleaseMedium, string>;
  filmReleaseMedium: Record<FilmReleaseMedium, string>;
  filmReleasePackaging: Record<FilmReleasePackaging, string>;
}

interface User {
  username: string;
  email: string;
  provider?: string;
  -password?: string;
  -resetPasswordToken?: string;
  -confirmationToken?: string;
  confirmed: boolean;
  blocked: boolean;
  myBooks: MyBook[];
  myBookReleases: MyBookRelease[];
  myFilms: Film[];
  myFilmReleases: MyFilmRelease[];
  myPositions: MyPosition[];
}

' Medium
Medium }o---o{ Genre
Medium }o---o{ Country

' Book
Book }|---o{ Person
Book }o---o{ BookSeries
Book }o---o| BookRelease
BookRelease |o---o{ Country
BookRelease |o---o{ ReleaseCollection
BookRelease --- BookReleaseMedium

' Film
Film }|---o{ Person
Film }o---o{ Studio
Film }o---|{ FilmSeries
Film }o---|| FilmRelease
FilmRelease |o---o{ Country
FilmRelease |o---o{ Rating
FilmRelease |o---o{ ReleaseCollection
FilmRelease --- FilmReleaseMedium
FilmRelease --- FilmReleasePackaging

' MyBook
Book ---|| MyBook
MyBook |o--- MyPosition
BookRelease ---|| MyBookRelease
MyBookRelease |o--- MyPosition

' MyFilm
Film ---|| MyFilm
MyFilm |o--- MyPosition
FilmRelease ---|| MyFilmRelease
MyFilmRelease |o--- MyPosition

' User
MyBook ||---o{ User
MyBookRelease ||---o{ User
MyFilm ||---o{ User
MyFilmRelease ||---o{ User
MyPosition ||---o{ User

@enduml
